version: "3.9"

services:
  web:
    build: .
    restart: unless-stopped
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - faiss

  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: marketlounge_db
      POSTGRES_USER: Isaac
      POSTGRES_PASSWORD: 3410

  faiss:
    image: python:3.10-slim
    restart: unless-stopped
    volumes:
      - ./faiss_index:/app/faiss_index
    working_dir: /app
    command: sleep infinity

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  pgdata:
  static_volume:
