# Generated by Django 5.2.5 on 2025-08-13 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_alter_glossarynode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossarynode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
